### ISSUE TITLE
Copyright status

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/rgeolocate#14]
@oschwald : 

So, we're planning on throwing this package up to CRAN, the archiva-like thing for R. Something they've pushed back on with previous submissions is copyright status and how we're describing it.

At the moment we list, as authors, myself, @wrathematics , Maxmind, Ltd. and Pascal Gloor, with the latter two identified explicitly as copyright holders. We then have a distinct "copyright" metadata entry reading "MaxMind, Ltd. for the underlying libmaxmminddb library, and the package authors for all other content."

Is this acceptable at MaxMind's end? If so, could you confirm? That way we can address the CRAN administrators' worries/annoyances directly. If not, happy to make whatever tweaks you think are necessary.

**Comment by oschwald** [comment]
@Ironholds, as long as you are following the terms of the Apache 2 license and make it clear that the libmaxminddb files are distributed under the license, it should be fine. Based on what you said, it sounds like you are. (It is "MaxMind, Inc.", not "Ltd.", but that is inconsequential.)

@jasonketola, is there anything you want to add?

**Comment by Ironholds** [comment]
On Apache 2, the licensing statements are left intact and the package metadata is marked as "this package is under apache 2.0". Just to be on the safe side I'll incorporate a full version of the license (and fix the Inc. problem, too!)

**Comment by Ironholds** [comment]
Now done.

**Comment by jasonketola** [comment]
@Ironholds, thanks for asking. If you follow @oschwald's advice above, you're a-ok.

**Comment by Ironholds** [comment]
Great; thanks! With those patches and tweaks in I'll bundle it up and send it to CRAN.
