### ISSUE TITLE
Portability issues

### ISSUE THREAD

**Issue by wrathematics** [Ironholds/rgeolocate#15]
As noted by Professor Ripley, there are significant [warnings](www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/rgeolocate-00check.html) on Fedora with gcc:

```
maxminddb.h:77:18: warning: ISO C does not support ‘__int128’ type [-Wpedantic]
maxminddb.h:111:6: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
maxminddb.h:77:27: warning: ISO C++ does not support ‘__int128’ for ‘mmdb_uint128_t’ 
```

And related errors on Solaris, [x86](https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/rgeolocate-00install.html) and [sparc](https://www.r-project.org/nosvn/R.check/r-patched-solaris-sparc/rgeolocate-00install.html):

```
In file included from maxmind.h:2:0,
                 from maxmind.cpp:1:
maxminddb.h:75:66: error: unable to emulate ‘TI’
 typedef unsigned int mmdb_uint128_t __attribute__ ((__mode__(TI)));
                                                                  ^
*** Error code 1
make: Fatal error: Command failed for target `maxmind.o'
Current working directory /tmp/RtmpCIa4xv/R.INSTALL2abf1202a3d/rgeolocate/src
/opt/csw/gcc4/bin/g++ -m32 -I/home/ripley/R/gcc/include -DNDEBUG  -I/opt/csw/include -I/usr/local/include -I"/home/ripley/R/Lib32/Rcpp/include"   -fPIC  -O2  -c maxmind.cpp -o maxmind.o
In file included from maxmind.h:2:0,
                 from maxmind.cpp:1:
maxminddb.h:75:66: error: unable to emulate ‘TI’
 typedef unsigned int mmdb_uint128_t __attribute__ ((__mode__(TI)));
                                                                  ^
*** Error code 1
make: Fatal error: Command failed for target `maxmind.o'
Current working directory /tmp/RtmpCIa4xv/R.INSTALL2abf1202a3d/rgeolocate/src
ERROR: compilation failed for package ‘rgeolocate’
* removing ‘/home/ripley/R/Lib32/rgeolocate’
```

**Comment by wrathematics** [comment]
@Ironholds please assign to me and ping me in a few weeks if I haven't made progress (it means I probably forgot).

**Comment by Ironholds** [comment]
Shall do!

**Comment by Ironholds** [comment]
@wrathematics poooke. We're getting queries from CRAN on this and other issues and I'd like to be able to submit a bundled fix.

**Comment by oschwald** [comment]
Given that you are embedding and not even using the uint128 database type, it might be easiest to just set `MMDB_UINT128_USING_MODE` to `0` and `MMDB_UINT128_IS_BYTE_ARRAY` to `1` for all users.

**Comment by wrathematics** [comment]
Oh, that makes sense.  Would also simplify the build significantly.  I'll try that in a minute here.

Thanks!

**Comment by wrathematics** [comment]
Wait, I seem to recall having trouble setting `MMDB_UINT128_USING_MODE` to `0` on win64.

@Ironholds, do you have a win64 test vm?  I think all of mine are win32...

Edit: for clarity, I had a win64 vm at my old job, but no longer have the rights to use that vm.

**Comment by oschwald** [comment]
`MMDB_UINT128_USING_MODE` [isn't even used](https://github.com/Ironholds/rgeolocate/blob/cfd74bdb0ffd42534aad12511a30a769b50d34ce/src/maxminddb.h#L73) if `MMDB_UINT128_IS_BYTE_ARRAY` is set to 1. I am not sure your existing win64 configuration is any different than your win32 one.

**Comment by Ironholds** [comment]
@wrathematics I do! I won't be able to test it for a couple hours but I actually have a win64 _partition_

**Comment by Ironholds** [comment]
@wrathematics okay, what's the status of the compile errors? I'd like to get a new release out with as many fixed as possible to appease the CRAN gods. If we're not all the way there, that's fine as long as we're in a place where we can point to progress.

**Comment by wrathematics** [comment]
@ironholds Thought I was waiting on you.  I need the R CMD check logs from a Linux machine that fails (try travis), and solaris if you can manage it.

**Comment by Ironholds** [comment]
Gotcha! I've tried Travis and it works like a charm; I think(?) I emailed you the Solaris login (did I not? Can resend)

**Comment by Ironholds** [comment]
@wrathematics per Twitter user "Installed with no hurdles on Fedora 22, but "test_check" complained that there were no tests found." which is odd. But, no hurdles!

**Comment by wrathematics** [comment]
@Ironholds Don't think I have the solaris login.  If you send it to me, I'll take a look at what the deal is.  I'm really wondering if dropping the `MMDB_UINT128_USING_MODE` stuff didn't fix it though.

**Comment by Ironholds** [comment]
Done! There's also the GCC warns, of course, but hopefully this will indeed fix.

**Comment by Ironholds** [comment]
I submitted to CRAN to clean up some unit test errors that were annoying people, and guess what? The Solaris issues are fixed! A couple of warns but otherwise no issue - https://cran.r-project.org/web/checks/check_results_rgeolocate.html

**Comment by wrathematics** [comment]
Makes sense.  But I don't see any warnings except on the few that haven't propagated from 0.4.1 to 0.5.0 yet.

If a warning pops up, I want to hear about it...eventually.  My schedule is inhuman right now 😭
