### ISSUE TITLE
Comparison across IP-Geo services

### ISSUE THREAD

**Issue by soodoku** [Ironholds/rgeolocate#16]
Dear O,

It would be great to compare IP-Geo services outputs for a large quasi-random set of IPs. It would be nice to know how much overlap there is between the services and in which places disagreement (we should measure the distance between lat/long) is the greatest. Nothing comprehensive can perhaps can come from this but it may provide useful insights.

**Comment by daroczig** [comment]
This article is pretty outdated, but might be useful for some related ideas and methods: http://www.caida.org/publications/papers/2011/geocompare-tr/geocompare-tr.pdf

**Comment by Ironholds** [comment]
Yeah, I thiiink this might be a PITA to do without access to the same datasets :(.
