### ISSUE TITLE
Improve the documentation to note we only ship with the country db, and link to where you can obtain the city db

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/rgeolocate#25]

**Comment by wabecerra** [comment]
Just to add that I finally got your point. After downloading the City database and in case you want to use it you need to copy it in this path: "C:\Users\user\Documents\R\win-library\3.2\rgeolocate\extdata"

Thanks for all your help,

**Comment by Ironholds** [comment]
No, I would seriously seriously recommend not doing that. At that point you're moving it into your R library. Those shouldn't be hand-modified.

Just point the function to where you've downloaded the file to, or included the file in your project. Do not copy the file to R. system.file() is explicitly for referring to files in installed R libraries. See ?system.file versus ?file.path (or just specifying the whole path yourself).

**Comment by wrathematics** [comment]
This would be a great example for the vignette imo.

**Comment by Ironholds** [comment]
Agreed!
