### ISSUE TITLE
does not work with ASN database from maxmind?

### ISSUE THREAD

**Issue by randomgambit** [Ironholds/rgeolocate#50]
Hello and thanks for this much needed R package!

It seems that `rgeolocate` cannot work with the `ASN` database shipped (freely) by maxmind.
I am getting

> Some field names you have provided are not supported and no data will be retrieved for them. 
> The
>             unsupported fields are: autonomous_system_organization
> 
> 
 Is that the case?
Thanks!

**Comment by Ironholds** [comment]
It should work fine; if you look at the docs for the maxmind function (`?maxmind`) you'll see that it expects 'asn' as a field name, rather than 'autonomous_system_organization'. Try that and let me know if it still objects?

Thanks!

**Comment by randomgambit** [comment]
thank you!
