### ISSUE TITLE
Field mismatch between ip_api() compared to ip-api.com directly

### ISSUE THREAD

**Issue by jlacko** [Ironholds/rgeolocate#57]
There seems to be a mismatch in fields returned by R function and the IP-API website; to reproduce please compare results from: `rgeolocate::ip_api("193.35.107.134")` and https://ip-api.com/#193.35.107.134 - the website results look sensible, but those from the R function not.

![Screenshot from 2019-10-17 16-42-00](https://user-images.githubusercontent.com/29260421/67019530-19196e80-f0fd-11e9-9f00-e65814423a6d.png)

**Comment by vladc** [comment]
This package parses the raw JSON line by line, and we've recently changed the order of the returned fields.

I did some previous work on a new version, but I didn't finish performance improvements/testing. Can you please test this? I'll make a pull request if everything seems ok
https://github.com/vladc/rgeolocate/tree/batch

_disclaimer: part of ip-api staff_

**Comment by jlacko** [comment]
Thanks for your prompt reply!

The fields were not quite OK, but I was able to tweak them by rearranging the index. You have got a pull request.

Thanks again for taking care, I was able to work with your code - but the original raw parser was beyond my limited C++ knowledge.

**Comment by jlacko** [comment]
@vladc I have tried the batch branch (and not master as earlier) and yes, the results are correct.

**Comment by Ironholds** [comment]
Should now be fixed.
