### ISSUE TITLE
Undefined symbol "shm_open"

### ISSUE THREAD

**Issue by scriptkitty** [Ironholds/rgeolocate#59]
Hi,
loading rgeolocate fails with the following error:

```rgeolocate.so: undefined symbol: shm_open```

Apparently, this is due to R changing the default linking flags, and there's [already a pull request for it](https://github.com/Ironholds/rgeolocate/pull/56), but applying these changes locally does not resolve the issue for me.

Any help would be greatly appreciated.

**Comment by ivokwee** [comment]
Yes. I have the same issue. Is there a solution?

**Comment by ivokwee** [comment]
Compiling the shared library by hand, adding the -lrt, then copying the library to /usr/local/lib seems to work. How to put it in the R package code?

`g++ -shared -L/usr/lib64/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o rgeolocate.so IP2Loc_DBInterface.o IP2Location.o RcppExports.o ip2.o ip_to_df.o maxmind.o maxminddb.o rgeolocate.o -L/usr/lib64/R/lib -lR -lrt`

`cp rgeolocate.so /usr/local/lib/R/site-library/rgeolocate/libs/rgeolocate.so`

**Comment by Ironholds** [comment]
Should now be fixed.
